Totems HUD fixes
3arthqu4ke/3arthh4ck pull request #196
Opened 2022-08-31 16:47 UTC by Ozynt

2022-08-31 17:11 UTC, 3arthqu4ke commented
How exactly does this help? Maybe you could just do it the way we do it for armor?

2022-08-31 17:17 UTC, Ozynt commented
Sure, I will redo and just leave the settings name fix.

2022-08-31 17:20 UTC, 3arthqu4ke commented
Can you do Totems-Y-Offset instead? Spaces in setting names are annoying since they need to get escaped when typing a command.

2022-08-31 17:23 UTC, Ozynt commented
I added enableDepth at the end since it caused some wierd issue in the inventory for me.

2022-08-31 18:54 UTC, 3arthqu4ke requested changes

2022-08-31 18:54 UTC, 3arthqu4ke commented on src/main/java/me/earth/earthhack/impl/modules/client/hud/HUD.java
> +                int x = width / 2 - 8;
XOffsetSetting?

2022-08-31 18:55 UTC, Ozynt commented on src/main/java/me/earth/earthhack/impl/modules/client/hud/HUD.java
> +                int x = width / 2 - 8;
Sure but would be pretty cursed

2022-08-31 21:07 UTC, 3arthqu4ke commented on src/main/java/me/earth/earthhack/impl/modules/client/hud/HUD.java
> +                int x = width / 2 - 8;
¯\_(ツ)_/¯

2022-08-31 21:51 UTC, 3arthqu4ke commented on src/main/java/me/earth/earthhack/impl/modules/client/hud/HUD.java
> +                int x = width / 2 - 8;
No just for small adjustments. I felt like int x = width / 2 - 7; was fine, but if you dont make a setting for small offsets.

2022-08-31 21:51 UTC, 3arthqu4ke commented on src/main/java/me/earth/earthhack/impl/modules/client/hud/HUD.java
> +                int x = width / 2 - 8;
You can do big offsets too idc

2022-09-01 04:55 UTC, Ozynt commented on src/main/java/me/earth/earthhack/impl/modules/client/hud/HUD.java
> +                int x = width / 2 - 8;
Ok I will add a small one in a few hours.

2022-09-01 07:16 UTC, 3arthqu4ke approved these changes

2022-09-01 07:17 UTC, merged