Dark & Light toggle switch button
3arthqu4ke/3arthh4ck pull request #265
Opened 2022-09-16 02:43 UTC by TwoThreeTwo

#254 

Things added:

1.-Toggle switch
2.-Full compatability across all devices (Hopefully, it works with my login screen lol, https://www.github.com/twothreetwo/website-login-screen)
3.-JQuery & Script to allow the transiton between Dark and Light to occur (I had to get a lot of help lol, might be bad code but it works :) )
4.- Made code scrumptious not delicious c :

Note from me:
Sorry for making the CSS Code well over 300 lines, it just works like that lol
but, this projec ultimately won't blind you cuz u can switch between dark and light which is pretty cool, it also uses transition speeds to make the process **super sexy**.

Here's the video providing you a preview of what it actually does :P

https://streamable.com/as86t5 
Any questions reach me on Two#6969 :)

2022-09-16 03:13 UTC, TwoThreeTwo commented
@3arthqu4ke , idk if there's any issues with it, should work but please check it with ur device to see if it actually works, afaik it works with chrome on 1920x1080 resolution laptop

2022-09-16 07:07 UTC, 3arthqu4ke requested changes

2022-09-16 07:07 UTC, 3arthqu4ke commented on script.js
> +    tempDisableAnim();
Dont you need to define this function somewhere?

2022-09-16 07:07 UTC, 3arthqu4ke commented on script.js
> +  refreshFavicon();
Shouldnt this function be defined somewhere?

2022-09-16 07:09 UTC, 3arthqu4ke commented
This is very cool, thanks for contributing. For some reason the Light - Dark button does not work on mobile for me. It works on my desktop with Chrome Devtools to see the mobile page tho 🤔

2022-09-16 12:20 UTC, TwoThreeTwo commented
I'll fix up the things u requested when I'm not in school or not busy, might be a while

2022-09-16 20:10 UTC, mdo992 commented
sometimes i can’t understand people’s motives

2022-09-16 22:07 UTC, TwoThreeTwo commented
> This is very cool, thanks for contributing. For some reason the Light - Dark button does not work on mobile for me. It works on my desktop with Chrome Devtools to see the mobile page tho 🤔

Could be due to different web browsers, like Chrome works on laptop but idk it works with safari or Opera, also the throttling could effect it somehow, but I'll do some debugging in a bit most likely will be ready by next week but, I may have to close this PR because it'll take a bit b4 I can actually have time to do anything Web Development related, school has started and I have too much homework lol

2022-09-16 22:09 UTC, TwoThreeTwo commented
Also, most of this other stuff was included in an old project of mine which was the first time I tried using JS, the ppl who helped me a bit did send some code to fix some issues but ig it included some other code. I can probably just spend a good while clearing the useless js

2022-09-16 23:59 UTC, TwoThreeTwo commented
> sometimes i can’t understand people’s motives

I just get bored

2022-09-17 07:40 UTC, 3arthqu4ke commented
Its fine, its fine! Just leave this PR open. Take as much time as you want maybe my phone is just trash.

2022-09-26 16:31 UTC, TwoThreeTwo commented
update on this, I'm just gonna rewrite it with a more simplistic basic bitch design with minimal js and css lol, I'll do it in a bit

2022-09-26 23:11 UTC, TwoThreeTwo commented
This'll be just a simple little basic btn with 4 lines of js instead of 200 lines lol

2022-09-27 00:22 UTC, TwoThreeTwo commented
@3arthqu4ke just changed up the design with a good ol' Click Me button made with js.

Reason why I built it with js? just easier lol, i watched 5 minutes of a js video and created that, the function I just had helped with a friend, overall should work WITH LITERALLY FUCKING ANYTHING.

2022-09-27 02:18 UTC, TwoThreeTwo commented
Updated the js code to just refer to button.style = `foo` because it looks cleaner also i just discovered it lol

2022-09-30 20:38 UTC, 3arthqu4ke commented
Uhm, whenever I press space it toggles dark/light mode. And the button at the bottom says "Click Me"?

2022-09-30 20:40 UTC, 3arthqu4ke commented
![unknown_2022 09 30-22 38](https://user-images.githubusercontent.com/56741599/193352892-33996ef8-8c1d-4864-9321-3a297c58c182.gif)

Every jump it switches

2022-09-30 20:42 UTC, mdo992 commented
> Uhm, whenever I press space it toggles dark/light mode. And the button at the bottom says "Click Me"

you could probably click away from the button and it’ll stop but the issue probably is that it’s still selected after you click it. @TwoThreeTwo

2022-09-30 20:44 UTC, TwoThreeTwo commented
> ![unknown_2022 09 30-22 38](https://user-images.githubusercontent.com/56741599/193352892-33996ef8-8c1d-4864-9321-3a297c58c182.gif)
> 
> 
> 
> Every jump it switches
> 
> 
I'm jus gonna close this and reopen it later if I ever try to fix it

2022-09-30 20:44 UTC, closed without merging