Add "Slime" setting to NoSlow
3arthqu4ke/3arthh4ck pull request #351
Opened 2023-01-31 20:02 UTC by nukiz

Setting allows for fast movement while walking/running on slime blocks. A few too many commits cuz i was tinkering around a bit.

2023-01-31 21:58 UTC, nukiz commented
Closes issue #324 btw.

2023-02-01 17:00 UTC, 3arthqu4ke requested changes

2023-02-01 17:00 UTC, 3arthqu4ke commented on src/main/java/me/earth/earthhack/impl/core/mixins/block/MixinBlockSlime.java
> +            (NoSlowDown.class, BooleanSetting.class, "Slime", true);
```suggestion
            (NoSlowDown.class, BooleanSetting.class, "Slime", false);
```

2023-02-01 18:54 UTC, 3arthqu4ke approved these changes

2023-02-01 18:54 UTC, merged