Crystalchams linewidth
3arthqu4ke/3arthh4ck pull request #55
Opened 2022-05-04 19:19 UTC by 15360enes

looks cool

2022-05-05 08:46 UTC, GurteX commented
i think it's fine

2022-05-06 14:21 UTC, 3arthqu4ke requested changes

2022-05-06 14:21 UTC, 3arthqu4ke commented on src/main/java/me/earth/earthhack/impl/modules/render/crystalchams/CrystalChams.java
> +            register(new NumberSetting<>("LineWidth" , 1f , 0.1f , 4f));
lowerCamelCase please, start LineWidth with a lower case l

2022-05-06 21:03 UTC, 3arthqu4ke approved these changes

2022-05-06 21:04 UTC, merged