changeable hud
3arthqu4ke/3arthh4ck pull request #9
Opened 2022-04-16 22:53 UTC by 15360enes

if you turn on logover it will render logo with version crazy

2022-04-17 16:48 UTC, 3arthqu4ke requested changes

2022-04-17 16:48 UTC, 3arthqu4ke commented on src/main/java/me/earth/earthhack/impl/modules/client/hud/HUD.java
> +        if (logo.getValue() || logover.getValue()) {
```java
if (logo.getValue()) {
```
instead pls.

2022-04-18 19:10 UTC, 15360enes commented
I dont know how github works how do I implement this to my pull req

2022-04-18 19:12 UTC, 3arthqu4ke commented
Just make another commit where you fix it, the PR will be updated.

2022-04-18 20:41 UTC, 15360enes commented
I think i did it

2022-04-21 07:23 UTC, 3arthqu4ke approved these changes

2022-04-27 18:14 UTC, closed without merging